# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20180112_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='names',
            new_name='conference_name',
        ),
    ]
