# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20180112_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='conference_name',
            new_name='name',
        ),
    ]
